const projects = [
    // {
    //     title: "Proton",
    //     description: "Proton is a multi-purpose discord bot, focused on advanced moderation and logging, tickets, levels all of witch can be managed from a dashboard.",
    //     thumbnail: "https://cdn.discordapp.com/attachments/810932922306789406/902667128811970620/proton.png",
    //     stack: ["svelte", "express", "nodedotjs"],
    //     code: "https://github.com/thereal-atom/proton",
    //     live: "https://protonmoderation.com",
    // },
    // {
    //     title: "openai.js",
    //     description: "openai.js is a JavaScript wrapper for the openai api. Has many functions such as translate, chat, sentiment analysis, semantic search and more.",
    //     thumbnail: "https://cdn.discordapp.com/attachments/810932922306789406/902673209378340904/Screenshot_2021-10-26_23_40_42.png",
    //     stack: ["openai", "javascript"],
    //     code: "https://github.com/thereal-atom/openai.js",
    //     live: "https://openaijs.org",
    // },
    {
        title: "Alertbot",
        description: "Alertbot allows you to create templates to enable alerting with maximum customisability. You can fully edit what your alert embed looks like and you can add parameters to the template.",
        thumbnail: "https://media.discordapp.net/attachments/967845567612989462/1010653281300795452/alertbot.png?width=1251&height=608",
        stack: ["tailwindcss", "typescript", "svelte", "nodedotjs"],
        code: "https://github.com/thereal-atom/alertbotxyz",
        live: "https://alert-bot.xyz",
    },
    // {
    //     title: "64-bit os",
    //     description: "Super simple 64-bit operating system built with assembly and C. Can only display text for now but i plan on upgrading it in the future perhaps with a command line.",
    //     thumbnail: "https://cdn.discordapp.com/attachments/810932922306789406/902823829255094322/Screenshot_2021-10-27_09_39_12.png",
    //     stack: ["assembly", "docker", "c"],
    //     code: "https://github.com/thereal-atom/os",
    //     live: "https://github.com/thereal-atom/os",
    // },
    // {
    //     title: "rustkv",
    //     description: "Simple in memory key-vale store similar to redis, with focus on good documentation and ease of use. This project was made primarily for learning rust and learning about database architecture.",
    //     thumbnail: "https://cdn.discordapp.com/attachments/889223726468579341/962667377491865630/Screenshot_from_2022-04-10_11-56-09.png",
    //     stack: ["rust"],
    //     code: "https://github.com/thereal-atom/rustkv",
    //     live: "https://github.com/thereal-atom/rustkv",
    // },
    {
        title: "Promess",
        description: "Promess is a project management software with focus on SaaS businesses. Promess brings together all your project management needs into one dashboard: tasks, files, chat, calendar, analytics, revenue, metrics and more.",
        thumbnail: "https://media.discordapp.net/attachments/967845567612989462/1010653281611153418/promess.png?width=1237&height=608",
        stack: ["tailwindcss", "typescript", "svelte", "nodedotjs"],
        code: "https://github.com/thereal-atom/promesstech",
        live: "https://promess.netlify.app",
    },
    {
        title: "Tempbot",
        description: "Tempbot allows you to create and manage temporary roles, channels and vcs as well as self roles and tickets. You can view and config them from a web dashboard",
        thumbnail: "https://cdn.discordapp.com/attachments/810932922306789406/899733066937946122/Frame_2.png",
        stack: ["tailwindcss", "typescript", "svelte", "nodedotjs"],
        code: "https://github.com/thereal-atom/tempbot-bot",
        live: "https://temp-bot.netlify.app",
    },
    {
        title: "papr",
        description: "papr is a cryptcurrency paper trading platform. You can open/close positions, view charts, view your holdings and more. It uses firebase for auth.",
        thumbnail: "https://cdn.discordapp.com/attachments/810932922306789406/902675407202041876/Screenshot_2021-10-26_23_49_32.png",
        stack: ["firebase", "express", "react", "mongodb"],
        code: "https://github.com/thereal-atom/papr",
        live: "https://papr-invest.co.uk",
    },
];

export default projects;